"""empty message

Revision ID: 0b759ab56910
Revises: 5848f6d8c7f4
Create Date: 2022-08-18 11:51:34.045381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0b759ab56910'
down_revision = '5848f6d8c7f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website', sa.String(length=120), nullable=True))
    op.drop_column('artist', 'website_link')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('website_link', sa.VARCHAR(length=120), autoincrement=False, nullable=False))
    op.drop_column('artist', 'website')
    # ### end Alembic commands ###
