"""empty message

Revision ID: f99e798e1d9d
Revises: 43e882d2ef08
Create Date: 2022-08-13 00:54:24.220376

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f99e798e1d9d'
down_revision = '43e882d2ef08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('artist', sa.Column('seeking_description', sa.String(), nullable=True))
    op.add_column('artist', sa.Column('address', sa.String(length=120), nullable=False))
    op.add_column('venue', sa.Column('seeking_description', sa.String(), nullable=True))
    op.alter_column('venue', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('venue', 'image_link',
               existing_type=sa.VARCHAR(length=500),
               nullable=True)
    op.drop_column('venue', 'seeking_description')
    op.drop_column('artist', 'address')
    op.drop_column('artist', 'seeking_description')
    # ### end Alembic commands ###
